# Libraries 

In [95]:
from sklearn.datasets import load_breast_cancer
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

In [96]:
data = load_breast_cancer()

In [97]:
df = pd.DataFrame(columns=data.feature_names,data=data.data)

In [98]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null

In [99]:
X = data.data

y = data.target 

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X_train , X_test , y_train, y_test = train_test_split(X,y,test_size=0.40,random_state=42)


In [102]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

In [103]:
model = gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)

In [104]:
print(y_pred)

[1 0 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 1 1 0 0 0 1 1 1 0 1 1 0 0 1 0 1 1 0 1 0 0
 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0
 0 1 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1
 0 0 1 1 0 1]


In [105]:
from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,y_pred))

print(50*"*")

print(classification_report(y_test,y_pred))

[[ 73   7]
 [  4 144]]
**************************************************
              precision    recall  f1-score   support

           0       0.95      0.91      0.93        80
           1       0.95      0.97      0.96       148

    accuracy                           0.95       228
   macro avg       0.95      0.94      0.95       228
weighted avg       0.95      0.95      0.95       228



# Confusion Matrix
* True Positives: TPs are the cases when the actual class of data point was 1 and
the predicted is also 1.
* True Negatives: TNs are the cases when the actual class of the data point was 0
and the predicted is also 0.
*  False Positives: FPs are the cases when the actual class of data point was 0 and
the predicted is also 1.
* False Negatives: FNs are the cases when the actual class of the data point was 1
and the predicted is also 0.

# Classification Report

* **Precision** : It may be defined as how many of the returned
documents are correct.
* **Recall or Sensitivity** : It may be defined as how many of the positives do the model return.
* **f1-score** : It gives a combined idea about Precision and Recall metrics. It is maximum when Precision is equal to Recall.

# Class Imbalance Problem

In [106]:
import pandas as pd
from sklearn.datasets import make_classification

# Generate synthetic imbalanced binary classification dataset
X, y = make_classification(
    n_samples=1000,           # Total number of rows
    n_features=5,             # Total features
    n_informative=3,         # Useful features for prediction
    n_redundant=1,           # Correlated features
    weights=[0.90, 0.10],    # Imbalance ratio: 90% Class 0 (Majority), 10% Class 1 (Minority)
    flip_y=0.01,             # Noise level (1% labels flipped)
    random_state=42
)

# Convert into a Pandas DataFrame
feature_cols = [f"feature_{i+1}" for i in range(X.shape[1])]
df = pd.DataFrame(X, columns=feature_cols)
df["target"] = y

# Inspect class distribution
print("Class breakdown:")
print(df["target"].value_counts(normalize=True))    

df.head()

X = df[["feature_1","feature_2","feature_3","feature_4","feature_5"]]

y = df.target

X_train , X_test , y_train, y_test = train_test_split(X,y,test_size=0.40,random_state=42)

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train,y_train)

y_pred = gnb.predict(X_test)

from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,y_pred))

print(50*"*")

print(classification_report(y_test,y_pred))

Class breakdown:
target
0    0.898
1    0.102
Name: proportion, dtype: float64
[[351   7]
 [ 16  26]]
**************************************************
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       358
           1       0.79      0.62      0.69        42

    accuracy                           0.94       400
   macro avg       0.87      0.80      0.83       400
weighted avg       0.94      0.94      0.94       400



# How To Solve The Problem ? 

Balancing the classes’ acts as a solution to imbalanced classes. The main objective of
balancing the classes is to either increase the frequency of the minority class or decrease
the frequency of the majority class. Following are the approaches to solve the issue of
imbalances classes:

# Re-Sampling
Re-sampling is a series of methods used to reconstruct the sample data sets - both training
sets and testing sets. Re-sampling is done to improve the accuracy of model. Following
are some re-sampling techniques:

## Random Under-Sampling
* This technique aims to balance class distribution by
randomly eliminating majority class examples. This is done until the majority and
minority class instances are balanced out.

In [107]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(sampling_strategy="auto",random_state=42)

X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)

gnb.fit(X_train_resampled,y_train_resampled)

y_pred = gnb.predict(X_test)

from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,y_pred))

print(50*"*")

print(classification_report(y_test,y_pred))


[[318  40]
 [  4  38]]
**************************************************
              precision    recall  f1-score   support

           0       0.99      0.89      0.94       358
           1       0.49      0.90      0.63        42

    accuracy                           0.89       400
   macro avg       0.74      0.90      0.78       400
weighted avg       0.94      0.89      0.90       400



In [108]:
print("Original train set class balance:\n", pd.Series(y_train).value_counts())
print("\nResampled train set class balance:\n", pd.Series(y_train_resampled).value_counts())

Original train set class balance:
 target
0    540
1     60
Name: count, dtype: int64

Resampled train set class balance:
 target
0    60
1    60
Name: count, dtype: int64


## Random Over-Sampling
*  This technique aims to balance class distribution by
increasing the number of instances in the minority class by replicating them.

In [109]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(sampling_strategy="auto",random_state=42)

X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

gnb.fit(X_train_resampled,y_train_resampled)

y_pred = gnb.predict(X_test)

from sklearn.metrics import classification_report , confusion_matrix

print(confusion_matrix(y_test,y_pred))

print(50*"*")

print(classification_report(y_test,y_pred))




[[324  34]
 [  4  38]]
**************************************************
              precision    recall  f1-score   support

           0       0.99      0.91      0.94       358
           1       0.53      0.90      0.67        42

    accuracy                           0.91       400
   macro avg       0.76      0.90      0.81       400
weighted avg       0.94      0.91      0.92       400



In [110]:
print("Original train set class balance:\n", pd.Series(y_train).value_counts())
print("\nResampled train set class balance:\n", pd.Series(y_train_resampled).value_counts())

Original train set class balance:
 target
0    540
1     60
Name: count, dtype: int64

Resampled train set class balance:
 target
0    540
1    540
Name: count, dtype: int64


__**The main advantage of this method is that there would be no loss of useful information.
But on the other hand, it has the increased chances of over-fitting because it replicates
the minority class events.**__